DROP DATABASE IF EXISTS notetorious;
CREATE DATABASE notetorious;

\c notetorious;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR (50) NOT NULL UNIQUE,
  email VARCHAR (355) NOT NULL UNIQUE,
  password VARCHAR (50) NOT NULL,
  profile_pic VARCHAR
);

CREATE TABLE notebooks (
  id SERIAL PRIMARY KEY,
  author_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR (50) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  is_default BOOLEAN DEFAULT FALSE
);

CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  title VARCHAR (50) NOT NULL UNIQUE,
  body VARCHAR (2000) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  author_id INT REFERENCES users(id) ON DELETE CASCADE,
  notebook_id INT REFERENCES notebooks(id) ON DELETE CASCADE,
  favorited BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tags (
  id SERIAL PRIMARY KEY,
  name VARCHAR (50) NOT NULL UNIQUE
);

CREATE TABLE taggings (
  id SERIAL PRIMARY KEY,
  note_id INT REFERENCES notes(id) NOT NULL,
  tag_id INT REFERENCES tags(id) NOT NULL
);
