//Auth
export const RECEIVE_USER = "RECEIVE_USER";

//Notebooks
export const RECEIVE_ALL_NOTEBOOKS = "RECEIVE_ALL_NOTEBOOKS";
export const RECEIVE_ID_FOR_NOTE_SELECTED_FROM_ALL_NOTEBOOKS =
  "RECEIVE_ID_FOR_NOTE_SELECTED_FROM_ALL_NOTEBOOKS";

//Notes
export const RECEIVE_ALL_NOTES = "RECEIVE_ALL_NOTES";
export const TOGGLE_NEW_NOTE = "TOGGLE_NEW_NOTE";
export const RECEIVE_ALL_NOTES_FROM_SINGLE_NOTEBOOK =
  "RECEIVE_ALL_NOTES_FROM_SINGLE_NOTEBOOK";

//Tags
export const RECEIVE_ALL_TAGS = "RECEIVE_ALL_TAGS";
